export const LISTA_HERRAMIENTA_REQUEST = 'LISTA_HERRAMIENTA_REQUEST';
export const LISTA_HERRAMIENTA_SUCCESS = 'LISTA_HERRAMIENTA_SUCCESS';
export const LISTA_HERRAMIENTA_FAIL = 'LISTA_HERRAMIENTA_FAIL';

export const DETALLES_HERRAMIENTA_REQUEST = 'DETALLES_HERRAMIENTA_REQUEST';
export const DETALLES_HERRAMIENTA_SUCCESS = 'DETALLES_HERRAMIENTA_SUCCESS';
export const DETALLES_HERRAMIENTA_FAIL = 'DETALLES_HERRAMIENTA_FAIL';
export const DETALLES_HERRAMIENTA_RESET = 'DETALLES_HERRAMIENTA_RESET';

export const HERRAMIENTA_ELIMINAR_REQUEST = 'HERRAMIENTA_ELIMINAR_REQUEST';
export const HERRAMIENTA_ELIMINAR_SUCCESS = 'HERRAMIENTA_ELIMINAR_SUCCESS';
export const HERRAMIENTA_ELIMINAR_FAIL = 'HERRAMIENTA_ELIMINAR_FAIL';

export const HERRAMIENTA_CREAR_REQUEST = 'HERRAMIENTA_CREAR_REQUEST';
export const HERRAMIENTA_CREAR_SUCCESS = 'HERRAMIENTA_CREAR_SUCCESS';
export const HERRAMIENTA_CREAR_FAIL = 'HERRAMIENTA_CREAR_FAIL';
export const HERRAMIENTA_CREAR_RESET = 'HERRAMIENTA_CREAR_RESET';

export const HERRAMIENTA_UPDATE_REQUEST = 'HERRAMIENTA_UPDATE_REQUEST';
export const HERRAMIENTA_UPDATE_SUCCESS = 'HERRAMIENTA_UPDATE_SUCCESS';
export const HERRAMIENTA_UPDATE_FAIL = 'HERRAMIENTA_UPDATE_FAIL';
export const HERRAMIENTA_UPDATE_RESET = 'HERRAMIENTA_UPDATE_RESET';
