export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTRO_REQUEST = 'USER_REGISTRO_REQUEST';
export const USER_REGISTRO_SUCCESS = 'USER_REGISTRO_SUCCESS';
export const USER_REGISTRO_FAIL = 'USER_REGISTRO_FAIL';

export const USER_DETALLES_REQUEST = 'USER_DETALLES_REQUEST';
export const USER_DETALLES_SUCCESS = 'USER_DETALLES_SUCCESS';
export const USER_DETALLES_FAIL = 'USER_DETALLES_FAIL';
export const USER_DETALLES_RESET = 'USER_DETALLES_RESET';

export const USER_UPDATE_PERFIL_REQUEST = 'USER_UPDATE_PERFIL_REQUEST';
export const USER_UPDATE_PERFIL_SUCCESS = 'USER_UPDATE_PERFIL_SUCCESS';
export const USER_UPDATE_PERFIL_FAIL = 'USER_UPDATE_PERFIL_FAIL';
export const USER_UPDATE_PERFIL_RESET = 'USER_UPDATE_PERFIL_RESET';

export const USER_LISTA_REQUEST = 'USER_LISTA_REQUEST';
export const USER_LISTA_SUCCESS = 'USER_LISTA_SUCCESS';
export const USER_LISTA_FAIL = 'USER_LISTA_FAIL';
export const USER_LISTA_RESET = 'USER_LISTA_RESET';

export const USER_LISTA_BECARIOS_REQUEST = 'USER_LISTA_BECARIOS_REQUEST';
export const USER_LISTA_BECARIOS_SUCCESS = 'USER_LISTA_BECARIOS_SUCCESS';
export const USER_LISTA_BECARIOS_FAIL = 'USER_LISTA_BECARIOS_FAIL';

export const USER_ELIMINAR_REQUEST = 'USER_ELIMINAR_REQUEST';
export const USER_ELIMINAR_SUCCESS = 'USER_ELIMINAR_SUCCESS';
export const USER_ELIMINAR_FAIL = 'USER_ELIMINAR_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
