export const VALE_ADD_ITEM = 'VALE_ADD_ITEM';
export const VALE_REMOVE_ITEM = 'VALE_REMOVE_ITEM';
export const VALE_GUARDAR_INFO = 'VALE_GUARDAR_INFO';
export const VALE_RESET = 'VALE_RESET';

export const VALE_CREATE_REQUEST = 'VALE_CREATE_REQUEST';
export const VALE_CREATE_SUCCESS = 'VALE_CREATE_SUCCESS';
export const VALE_CREATE_FAIL = 'VALE_CREATE_FAIL';
export const VALE_CREATE_RESET = 'VALE_CREATE_FAIL';

export const VALE_DETALLES_REQUEST = 'VALE_DETALLES_REQUEST';
export const VALE_DETALLES_SUCCESS = 'VALE_DETALLES_SUCCESS';
export const VALE_DETALLES_FAIL = 'VALE_DETALLES_FAIL';
export const VALE_DETALLES_REMOVE_ITEM = 'VALE_DETALLES_REMOVE_ITEM';

export const VALE_FINALIZAR_REQUEST = 'VALE_FINALIZAR_REQUEST';
export const VALE_FINALIZAR_SUCCESS = 'VALE_FINALIZAR_SUCCESS';
export const VALE_FINALIZAR_FAIL = 'VALE_FINALIZAR_FAIL';
export const VALE_FINALIZAR_RESET = 'VALE_FINALIZAR_RESET';

export const MIS_VALES_REQUEST = 'MIS_VALES_REQUEST';
export const MIS_VALES_SUCCESS = 'MIS_VALES_SUCCESS';
export const MIS_VALES_FAIL = 'MIS_VALES_FAIL';
export const MIS_VALES_RESET = 'MIS_VALES_RESET';

export const LISTA_VALES_REQUEST = 'LISTA_VALES_REQUEST';
export const LISTA_VALES_SUCCESS = 'LISTA_VALES_SUCCESS';
export const LISTA_VALES_FAIL = 'LISTA_VALES_FAIL';
export const LISTA_VALES_RESET = 'LISTA_VALES_RESET';

export const LISTA_VALES_TIPO_REQUEST = 'LISTA_VALES_TIPO_REQUEST';
export const LISTA_VALES_TIPO_SUCCESS = 'LISTA_VALES_TIPO_SUCCESS';
export const LISTA_VALES_TIPO_FAIL = 'LISTA_VALES_TIPO_FAIL';
export const LISTA_VALES_TIPO_RESET = 'LISTA_VALES_TIPO_RESET';

export const UPDATE_VALE_PENDIENTE_REQUEST =
	'ACTUALIZAR_VALE_PENDIENTE_REQUEST';
export const UPDATE_VALE_PENDIENTE_SUCCESS =
	'ACTUALIZAR_VALE_PENDIENTE_SUCCESS';
export const UPDATE_VALE_PENDIENTE_FAIL = 'ACTUALIZAR_VALE_PENDIENTE_FAIL';
export const UPDATE_VALE_PENDIENTE_RESET = 'ACTUALIZAR_VALE_PENDIENTE_RESET';
export const VALE_PENDIENTE_REMOVE_ITEM = 'VALE_PENDIENTE_REMOVE_ITEM';
